version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
      - "go"
    schedule:
      interval: "weekly"
    groups:
      golangx:
        patterns:
          - "golang.org/x/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "actions"
    schedule:
      interval: "weekly"
    groups:
      artifacts:
        patterns:
          - "action/upload-artifact"
          - "action/download-artifact"