name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.head_ref, 'dependabot') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run commit lint
        uses: wagoid/commitlint-github-action@v6
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'