name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.head_ref, 'dependabot') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run commit lint
        uses: wagoid/commitlint-github-action@v6
  
  build:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'
    - name: Build
      run: make build

  spinit-unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.8.1
          go get github.com/onsi/gomega/...
          go mod tidy -v
      - name: Run unit tests
        run: make unit-tests

  spinit-integration-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.8.1
          go get github.com/onsi/gomega/...
          go mod tidy -v
      - name: Run integration tests
        run: make integration-tests

  success-all-test:
    needs:
      - spinit-unit-tests
      - spinit-integration-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "All Done"